// Multilingual content and small interactive enhancements for the static landing page.
const i18nData = {
    en: {
        "language-label": "Language",
        "nav-features": "Features",
        "nav-platforms": "Supported Sites",
        "hero-title": "Share Cleaner, Safer Links Instantly",
        "hero-subtitle": "A lightweight, privacy-focused web extension. Automatically strip tracking parameters and generate gorgeous, embed-friendly previews for X, Bilibili, Reddit, and Pixiv.",
        "store-chrome-small": "Source & install",
        "store-firefox-small": "Source & install",
        "store-safari-small": "Source & install",
        "store-app-small": "Mobile Web",
        "store-zip-small": "Developer Mode",
        "btn-chrome": "Chrome build notes",
        "btn-firefox": "Firefox build notes",
        "btn-safari": "Safari build notes",
        "btn-app": "Open mobile Web App",
        "btn-zip": "Download releases",
        "preview-original": "Original Link:",
        "preview-arrow": "⬇️ Strips trackers & rewrites host",
        "preview-vx": "Cleaned VX Link:",
        "url-original": "https://x.com/user/status/1234567890?s=20&t=tracker_code_abc",
        "url-vx": "https://vxtwitter.com/user/status/1234567890",
        "features-title": "Why Use VX Link Helper?",
        "feat1-title": "🔒 100% Local Processing",
        "feat1-desc": "Runs completely inside your browser sandbox. No telemetry, no backend analysis, and absolute offline privacy with data that belongs entirely to you.",
        "feat2-title": "✨ Flawless Preview Cards",
        "feat2-desc": "Converts regular URLs to optimized preview proxies like vxtwitter, ensuring media embeds render perfectly inside messaging clients like Discord and Telegram.",
        "feat3-title": "⚡ Native UI Injection",
        "feat3-desc": "Uses fast DOM observers to inject a sleek VX shortcut next to each supported site's original share controls.",
        "platforms-title": "Supported Domain Transformations",
        "table-th1": "Platform",
        "table-th2": "Original Domain",
        "table-th3": "Privacy / Embed Domain",
        "footer-docs": "Project notes",
        "footer-text": "VX Link Helper is fully open-source, local-only, and tracking-free.",
        "footer-privacy": "Privacy Policy",
        "p-title": "Privacy Policy",
        "p-intro": "VX Link Helper was built with user privacy as its core principle. This policy documents the local-only behavior of the extension:",
        "p-h1": "1. Zero Data Collection",
        "p-d1": "We <b>do not collect, store, transmit, or sell</b> any personal data, clipboard values, browsing history, or usage logs. There is no telemetry pipeline and no remote analytics service.",
        "p-h2": "2. Local-Only Processing",
        "p-d2": "All link cleanup and domain rewriting runs inside your browser sandbox on your own device. URLs are processed locally and remain under your control.",
        "p-h3": "3. Permission Transparency",
        "p-d3": "Requested browser permissions are limited to the features they enable:",
        "p-l1": "contextMenus: Adds the Copy VX Link action to the browser context menu.",
        "p-l2": "clipboardWrite: Writes the cleaned link back to your system clipboard.",
        "p-l3": "Specific host matches: Safely injects copy buttons only on supported websites.",
        "p-h4": "4. Store Statistics",
        "p-d4": "Distribution platforms such as the Chrome Web Store, Firefox Add-ons, Edge Add-ons, or Safari may provide maintainers with aggregated installation, version, region, or active-device statistics. Those statistics come from the stores themselves; VX Link Helper does not actively upload your links, clipboard contents, or browsing activity.",
        "back-home": "Back to Home",
        "meta-description": "A lightweight, privacy-focused extension that strips tracking parameters and generates embed-friendly links for X, Bilibili, Reddit, and Pixiv."
    },
    zh: {
        "language-label": "语言",
        "nav-features": "功能特点",
        "nav-platforms": "支持平台",
        "hero-title": "分享更干净、更安全的链接",
        "hero-subtitle": "轻量级、保护隐私的浏览器扩展。自动剥离各类隐藏追踪参数，并为 X、Bilibili、Reddit 和 Pixiv 生成对社交软件更友好的卡片预览链接。",
        "store-chrome-small": "查看源码",
        "store-firefox-small": "查看源码",
        "store-safari-small": "查看源码",
        "store-app-small": "手机 Web",
        "store-zip-small": "开发者模式",
        "btn-chrome": "Chrome 版本说明",
        "btn-firefox": "Firefox 版本说明",
        "btn-safari": "Safari 版本说明",
        "btn-app": "打开手机 Web App",
        "btn-zip": "下载发布包",
        "preview-original": "原始链接:",
        "preview-arrow": "⬇️ 自动净化参数并重写域名",
        "preview-vx": "VX 净化链接:",
        "url-original": "https://www.bilibili.com/video/BV1xx411c7xx/?spm_id_from=333.788&share_source=copy_web&vd_source=123456",
        "url-vx": "https://vxbilibili.com/video/BV1xx411c7xx/",
        "features-title": "为什么选择 VX Link Helper？",
        "feat1-title": "🔒 纯本地保护",
        "feat1-desc": "100% 运行在浏览器本地，不向外发起任何网络请求。在复制的瞬间剥离隐藏在链接内部的用户行为追踪令牌。",
        "feat2-title": "✨ 完美卡片渲染",
        "feat2-desc": "自动将支持的网站域名转换为兼容的预览代理（如 vxtwitter），确保在 Discord、Telegram 等聊天软件中直接展现完整的媒体卡片。",
        "feat3-title": "⚡ 原生级内嵌",
        "feat3-desc": "利用高效的 DOM 监听，无感地在目标网站原生分享按钮旁注入快捷的“VX”一键复制按钮，极速流畅。",
        "platforms-title": "已支持的域名转换",
        "table-th1": "平台",
        "table-th2": "原始域名",
        "table-th3": "转换后防追踪/卡片域名",
        "footer-docs": "项目说明",
        "footer-text": "VX Link Helper 承诺完全开源、本地运行且无任何潜在数据追踪。",
        "footer-privacy": "隐私政策",
        "p-title": "隐私政策",
        "p-intro": "VX Link Helper 扩展程序在开发设计上将用户的“绝对隐私”放在首位。本政策阐明了本扩展不涉及任何用户数据的处理逻辑：",
        "p-h1": "1. 零数据收集",
        "p-d1": "我们<b>不会收集、存储、上传、传输或销售</b>您的任何个人信息、浏览历史或剪贴板内容。扩展程序没有后台统计、没有行为分析脚本，更没有设立任何远程服务器。",
        "p-h2": "2. 本地化运行架构",
        "p-d2": "所有的链接参数剥离和重写操作（如过滤 Bilibili 追踪代码、重定向 Reddit 链接）全部由您本地设备的浏览器底层沙盒隔离执行，数据完全属于您自己。",
        "p-h3": "3. 权限合规说明",
        "p-d3": "本扩展申请的专用权限仅为实现对应原生功能，绝无滥用：",
        "p-l1": "contextMenus: 用于在右键菜单中生成“复制 VX 链接”选项。",
        "p-l2": "clipboardWrite: 用于将清洗干净的链接回写至系统剪贴板。",
        "p-l3": "特定主站域名匹配: 用于在被支持的网站上安全注入对应的复制按钮。",
        "p-h4": "4. 商店统计说明",
        "p-d4": "Chrome Web Store、Firefox Add-ons、Edge Add-ons 或 Safari 等分发平台可能向开发者提供聚合安装量、版本、地区或活跃设备统计。这些统计来自商店平台本身；VX Link Helper 扩展不会主动上传您的链接、剪贴板内容或浏览行为。",
        "back-home": "返回首页",
        "meta-description": "轻量级、保护隐私的浏览器扩展。自动剥离追踪参数，并为 X、Bilibili、Reddit 和 Pixiv 生成完美兼容 Discord/Telegram 的卡片预览链接。"
    },
    "zh-TW": {
        "language-label": "語言",
        "nav-features": "功能特色",
        "nav-platforms": "支援平台",
        "hero-title": "立即分享更乾淨、更安全的連結",
        "hero-subtitle": "輕量、重視隱私的瀏覽器擴充功能。自動移除追蹤參數，並為 X、Bilibili、Reddit 與 Pixiv 產生更適合社群軟體預覽的卡片連結。",
        "store-chrome-small": "原始碼與安裝",
        "store-firefox-small": "原始碼與安裝",
        "store-safari-small": "原始碼與安裝",
        "store-app-small": "手機 Web",
        "store-zip-small": "開發者模式",
        "btn-chrome": "Chrome 版本說明",
        "btn-firefox": "Firefox 版本說明",
        "btn-safari": "Safari 版本說明",
        "btn-app": "開啟手機 Web App",
        "btn-zip": "下載發行版本",
        "preview-original": "原始連結:",
        "preview-arrow": "⬇️ 移除追蹤並改寫網域",
        "preview-vx": "VX 淨化連結:",
        "url-original": "https://www.bilibili.com/video/BV1xx411c7xx/?spm_id_from=333.788&share_source=copy_web&vd_source=123456",
        "url-vx": "https://vxbilibili.com/video/BV1xx411c7xx/",
        "features-title": "為什麼選擇 VX Link Helper？",
        "feat1-title": "🔒 100% 本機處理",
        "feat1-desc": "完全在瀏覽器沙盒內執行，不收集遙測、不依賴後端分析，資料始終只屬於你。",
        "feat2-title": "✨ 完整預覽卡片",
        "feat2-desc": "將一般網址轉換為最佳化預覽代理網域，例如 vxtwitter，讓 Discord、Telegram 等聊天工具能正確顯示媒體卡片。",
        "feat3-title": "⚡ 原生介面注入",
        "feat3-desc": "使用快速 DOM 監聽，在支援網站的原生分享控制旁加入俐落的 VX 快捷按鈕。",
        "platforms-title": "支援的網域轉換",
        "table-th1": "平台",
        "table-th2": "原始網域",
        "table-th3": "隱私 / 預覽網域",
        "footer-docs": "專案說明",
        "footer-text": "VX Link Helper 完全開源、僅在本機執行，且不含任何追蹤。",
        "footer-privacy": "隱私權政策",
        "p-title": "隱私權政策",
        "p-intro": "VX Link Helper 以使用者隱私為核心原則。本政策說明此擴充功能的純本機行為：",
        "p-h1": "1. 零資料收集",
        "p-d1": "我們<b>不會收集、儲存、傳輸或販售</b>任何個人資料、剪貼簿內容、瀏覽紀錄或使用記錄，也沒有遙測或遠端分析服務。",
        "p-h2": "2. 僅在本機處理",
        "p-d2": "所有連結清理與網域改寫都在你裝置上的瀏覽器沙盒中完成，網址只在本機處理並由你掌控。",
        "p-h3": "3. 權限透明",
        "p-d3": "所需瀏覽器權限僅用於啟用對應功能：",
        "p-l1": "contextMenus: 在瀏覽器右鍵選單加入「複製 VX 連結」。",
        "p-l2": "clipboardWrite: 將清理後的連結寫回系統剪貼簿。",
        "p-l3": "特定主站網域匹配: 僅在支援網站安全注入複製按鈕。",
        "p-h4": "4. 商店統計說明",
        "p-d4": "Chrome Web Store、Firefox Add-ons、Edge Add-ons 或 Safari 等發佈平台可能向維護者提供彙總的安裝量、版本、地區或活躍裝置統計。這些統計來自商店平台本身；VX Link Helper 不會主動上傳你的連結、剪貼簿內容或瀏覽行為。",
        "back-home": "返回首頁",
        "meta-description": "輕量、重視隱私的擴充功能，可移除追蹤參數，並為 X、Bilibili、Reddit 與 Pixiv 產生適合預覽的連結。"
    },
    es: {
        "language-label": "Idioma",
        "nav-features": "Funciones",
        "nav-platforms": "Sitios compatibles",
        "hero-title": "Comparte enlaces más limpios y seguros al instante",
        "hero-subtitle": "Una extensión ligera y enfocada en la privacidad. Elimina parámetros de seguimiento y genera vistas previas optimizadas para X, Bilibili, Reddit y Pixiv.",
        "store-chrome-small": "Código e instalación",
        "store-firefox-small": "Código e instalación",
        "store-safari-small": "Código e instalación",
        "store-app-small": "Web móvil",
        "store-zip-small": "Modo desarrollador",
        "btn-chrome": "Notas para Chrome",
        "btn-firefox": "Notas para Firefox",
        "btn-safari": "Notas para Safari",
        "btn-app": "Abrir Web App móvil",
        "btn-zip": "Descargar versiones",
        "preview-original": "Enlace original:",
        "preview-arrow": "⬇️ Elimina rastreadores y reescribe el dominio",
        "preview-vx": "Enlace VX limpio:",
        "url-original": "https://x.com/user/status/1234567890?s=20&t=tracker_code_abc",
        "url-vx": "https://vxtwitter.com/user/status/1234567890",
        "features-title": "¿Por qué usar VX Link Helper?",
        "feat1-title": "🔒 Procesamiento 100% local",
        "feat1-desc": "Funciona por completo dentro del sandbox del navegador. Sin telemetría, sin análisis backend y con privacidad offline absoluta.",
        "feat2-title": "✨ Tarjetas de vista previa perfectas",
        "feat2-desc": "Convierte URLs normales en dominios proxy optimizados como vxtwitter, para que Discord, Telegram y otros clientes muestren bien los medios.",
        "feat3-title": "⚡ Integración nativa en la interfaz",
        "feat3-desc": "Usa observadores DOM rápidos para añadir un atajo VX junto a los controles de compartir de cada sitio compatible.",
        "platforms-title": "Transformaciones de dominio compatibles",
        "table-th1": "Plataforma",
        "table-th2": "Dominio original",
        "table-th3": "Dominio de privacidad / vista previa",
        "footer-docs": "Notas del proyecto",
        "footer-text": "VX Link Helper es completamente open source, local y sin rastreo.",
        "footer-privacy": "Política de privacidad",
        "p-title": "Política de privacidad",
        "p-intro": "VX Link Helper se creó con la privacidad como principio central. Esta política documenta su comportamiento local:",
        "p-h1": "1. Cero recopilación de datos",
        "p-d1": "<b>No recopilamos, almacenamos, transmitimos ni vendemos</b> datos personales, contenido del portapapeles, historial o registros de uso. No hay telemetría ni analítica remota.",
        "p-h2": "2. Procesamiento solo local",
        "p-d2": "Toda la limpieza de enlaces y reescritura de dominios ocurre en el sandbox del navegador en tu dispositivo. Las URLs se procesan localmente.",
        "p-h3": "3. Transparencia de permisos",
        "p-d3": "Los permisos solicitados se limitan a las funciones que habilitan:",
        "p-l1": "contextMenus: añade la acción Copiar enlace VX al menú contextual del navegador.",
        "p-l2": "clipboardWrite: escribe el enlace limpio en el portapapeles del sistema.",
        "p-l3": "Coincidencias de hosts específicos: inyecta botones solo en sitios compatibles.",
        "p-h4": "4. Estadísticas de las tiendas",
        "p-d4": "Plataformas de distribución como Chrome Web Store, Firefox Add-ons, Edge Add-ons o Safari pueden ofrecer a los mantenedores estadísticas agregadas de instalaciones, versiones, regiones o dispositivos activos. Esas estadísticas provienen de las propias tiendas; VX Link Helper no sube activamente tus enlaces, contenido del portapapeles ni actividad de navegación.",
        "back-home": "Volver al inicio",
        "meta-description": "Extensión ligera y privada que elimina parámetros de seguimiento y genera enlaces con vista previa para X, Bilibili, Reddit y Pixiv."
    },
    ar: {
        "language-label": "اللغة",
        "nav-features": "الميزات",
        "nav-platforms": "المواقع المدعومة",
        "hero-title": "شارك روابط أنظف وأكثر أماناً فوراً",
        "hero-subtitle": "إضافة خفيفة تركز على الخصوصية. تزيل معلمات التتبع وتولّد معاينات مناسبة لـ X وBilibili وReddit وPixiv.",
        "store-chrome-small": "المصدر والتثبيت",
        "store-firefox-small": "المصدر والتثبيت",
        "store-safari-small": "المصدر والتثبيت",
        "store-app-small": "ويب الجوال",
        "store-zip-small": "وضع المطور",
        "btn-chrome": "ملاحظات Chrome",
        "btn-firefox": "ملاحظات Firefox",
        "btn-safari": "ملاحظات Safari",
        "btn-app": "فتح تطبيق الويب للجوال",
        "btn-zip": "تنزيل الإصدارات",
        "preview-original": "الرابط الأصلي:",
        "preview-arrow": "⬇️ إزالة التتبع وإعادة كتابة النطاق",
        "preview-vx": "رابط VX المنظف:",
        "url-original": "https://x.com/user/status/1234567890?s=20&t=tracker_code_abc",
        "url-vx": "https://vxtwitter.com/user/status/1234567890",
        "features-title": "لماذا تستخدم VX Link Helper؟",
        "feat1-title": "🔒 معالجة محلية 100%",
        "feat1-desc": "تعمل بالكامل داخل صندوق عزل المتصفح. لا قياسات، لا تحليل خلفي، وخصوصية محلية كاملة.",
        "feat2-title": "✨ بطاقات معاينة مثالية",
        "feat2-desc": "تحوّل الروابط العادية إلى نطاقات معاينة محسّنة مثل vxtwitter كي تظهر الوسائط بشكل صحيح في Discord وTelegram.",
        "feat3-title": "⚡ دمج واجهة أصلي",
        "feat3-desc": "تستخدم مراقبات DOM سريعة لإضافة اختصار VX بجانب عناصر المشاركة الأصلية في المواقع المدعومة.",
        "platforms-title": "تحويلات النطاق المدعومة",
        "table-th1": "المنصة",
        "table-th2": "النطاق الأصلي",
        "table-th3": "نطاق الخصوصية / المعاينة",
        "footer-docs": "ملاحظات المشروع",
        "footer-text": "VX Link Helper مفتوح المصدر بالكامل، يعمل محلياً فقط، وخالٍ من التتبع.",
        "footer-privacy": "سياسة الخصوصية",
        "p-title": "سياسة الخصوصية",
        "p-intro": "صُمم VX Link Helper على مبدأ الخصوصية أولاً. توضح هذه السياسة أن الإضافة تعمل محلياً فقط:",
        "p-h1": "1. لا جمع للبيانات",
        "p-d1": "نحن <b>لا نجمع ولا نخزن ولا ننقل ولا نبيع</b> أي بيانات شخصية أو محتوى الحافظة أو سجل التصفح أو سجلات الاستخدام. لا توجد قياسات أو تحليلات بعيدة.",
        "p-h2": "2. معالجة محلية فقط",
        "p-d2": "كل تنظيف الروابط وإعادة كتابة النطاقات يحدث داخل صندوق عزل المتصفح على جهازك. تبقى الروابط تحت تحكمك.",
        "p-h3": "3. شفافية الأذونات",
        "p-d3": "تقتصر أذونات المتصفح المطلوبة على الميزات التي تفعّلها:",
        "p-l1": "contextMenus: يضيف خيار نسخ رابط VX إلى قائمة المتصفح السياقية.",
        "p-l2": "clipboardWrite: يكتب الرابط المنظف إلى حافظة النظام.",
        "p-l3": "مطابقة مضيفين محددين: يحقن أزرار النسخ فقط في المواقع المدعومة.",
        "p-h4": "4. إحصاءات المتاجر",
        "p-d4": "قد توفر منصات التوزيع مثل Chrome Web Store وFirefox Add-ons وEdge Add-ons أو Safari للمشرفين إحصاءات مجمعة عن التثبيت أو الإصدارات أو المناطق أو الأجهزة النشطة. تأتي هذه الإحصاءات من المتاجر نفسها؛ ولا يرفع VX Link Helper روابطك أو محتوى الحافظة أو نشاط التصفح بشكل نشط.",
        "back-home": "العودة للرئيسية",
        "meta-description": "إضافة خفيفة وخاصة تزيل معلمات التتبع وتولد روابط مناسبة للمعاينة لـ X وBilibili وReddit وPixiv."
    },
    pt: {
        "language-label": "Idioma",
        "nav-features": "Recursos",
        "nav-platforms": "Sites compatíveis",
        "hero-title": "Compartilhe links mais limpos e seguros instantaneamente",
        "hero-subtitle": "Uma extensão leve e focada em privacidade. Remove parâmetros de rastreamento e gera prévias otimizadas para X, Bilibili, Reddit e Pixiv.",
        "store-chrome-small": "Código e instalação",
        "store-firefox-small": "Código e instalação",
        "store-safari-small": "Código e instalação",
        "store-app-small": "Web móvel",
        "store-zip-small": "Modo desenvolvedor",
        "btn-chrome": "Notas para Chrome",
        "btn-firefox": "Notas para Firefox",
        "btn-safari": "Notas para Safari",
        "btn-app": "Abrir Web App móvel",
        "btn-zip": "Baixar releases",
        "preview-original": "Link original:",
        "preview-arrow": "⬇️ Remove rastreadores e reescreve o domínio",
        "preview-vx": "Link VX limpo:",
        "url-original": "https://x.com/user/status/1234567890?s=20&t=tracker_code_abc",
        "url-vx": "https://vxtwitter.com/user/status/1234567890",
        "features-title": "Por que usar o VX Link Helper?",
        "feat1-title": "🔒 Processamento 100% local",
        "feat1-desc": "Roda totalmente dentro do sandbox do navegador. Sem telemetria, sem análise em backend e com privacidade offline absoluta.",
        "feat2-title": "✨ Cartões de prévia perfeitos",
        "feat2-desc": "Converte URLs comuns em domínios de prévia otimizados como vxtwitter, garantindo mídia bem renderizada no Discord, Telegram e outros clientes.",
        "feat3-title": "⚡ Injeção nativa de UI",
        "feat3-desc": "Usa observadores DOM rápidos para inserir um atalho VX ao lado dos controles de compartilhamento dos sites compatíveis.",
        "platforms-title": "Transformações de domínio compatíveis",
        "table-th1": "Plataforma",
        "table-th2": "Domínio original",
        "table-th3": "Domínio de privacidade / prévia",
        "footer-docs": "Notas do projeto",
        "footer-text": "VX Link Helper é totalmente open source, local e sem rastreamento.",
        "footer-privacy": "Política de privacidade",
        "p-title": "Política de privacidade",
        "p-intro": "VX Link Helper foi criado com privacidade como princípio central. Esta política documenta seu comportamento local:",
        "p-h1": "1. Zero coleta de dados",
        "p-d1": "Nós <b>não coletamos, armazenamos, transmitimos ou vendemos</b> dados pessoais, conteúdo da área de transferência, histórico ou logs de uso. Não há telemetria nem análise remota.",
        "p-h2": "2. Processamento apenas local",
        "p-d2": "Toda limpeza de links e reescrita de domínios acontece no sandbox do navegador no seu dispositivo. As URLs são processadas localmente.",
        "p-h3": "3. Transparência de permissões",
        "p-d3": "As permissões solicitadas são limitadas às funções que ativam:",
        "p-l1": "contextMenus: adiciona Copiar link VX ao menu de contexto do navegador.",
        "p-l2": "clipboardWrite: grava o link limpo na área de transferência do sistema.",
        "p-l3": "Correspondências de hosts específicos: injeta botões apenas em sites compatíveis.",
        "p-h4": "4. Estatísticas das lojas",
        "p-d4": "Plataformas de distribuição como Chrome Web Store, Firefox Add-ons, Edge Add-ons ou Safari podem fornecer aos mantenedores estatísticas agregadas de instalação, versão, região ou dispositivos ativos. Essas estatísticas vêm das próprias lojas; o VX Link Helper não envia ativamente seus links, conteúdo da área de transferência ou atividade de navegação.",
        "back-home": "Voltar ao início",
        "meta-description": "Extensão leve e privada que remove parâmetros de rastreamento e gera links com prévia para X, Bilibili, Reddit e Pixiv."
    },
    fr: {
        "language-label": "Langue",
        "nav-features": "Fonctionnalités",
        "nav-platforms": "Sites pris en charge",
        "hero-title": "Partagez instantanément des liens plus propres et plus sûrs",
        "hero-subtitle": "Une extension légère axée sur la confidentialité. Elle supprime les paramètres de suivi et génère des aperçus optimisés pour X, Bilibili, Reddit et Pixiv.",
        "store-chrome-small": "Source et installation",
        "store-firefox-small": "Source et installation",
        "store-safari-small": "Source et installation",
        "store-app-small": "Web mobile",
        "store-zip-small": "Mode développeur",
        "btn-chrome": "Notes Chrome",
        "btn-firefox": "Notes Firefox",
        "btn-safari": "Notes Safari",
        "btn-app": "Ouvrir la Web App mobile",
        "btn-zip": "Télécharger les versions",
        "preview-original": "Lien original :",
        "preview-arrow": "⬇️ Supprime le suivi et réécrit le domaine",
        "preview-vx": "Lien VX nettoyé :",
        "url-original": "https://x.com/user/status/1234567890?s=20&t=tracker_code_abc",
        "url-vx": "https://vxtwitter.com/user/status/1234567890",
        "features-title": "Pourquoi utiliser VX Link Helper ?",
        "feat1-title": "🔒 Traitement 100 % local",
        "feat1-desc": "Fonctionne entièrement dans le bac à sable du navigateur. Aucune télémétrie, aucune analyse backend et une confidentialité hors ligne complète.",
        "feat2-title": "✨ Cartes d’aperçu impeccables",
        "feat2-desc": "Convertit les URL ordinaires en domaines d’aperçu optimisés comme vxtwitter, pour un rendu parfait dans Discord, Telegram et autres clients.",
        "feat3-title": "⚡ Injection d’interface native",
        "feat3-desc": "Utilise des observateurs DOM rapides pour ajouter un raccourci VX à côté des contrôles de partage des sites pris en charge.",
        "platforms-title": "Transformations de domaine prises en charge",
        "table-th1": "Plateforme",
        "table-th2": "Domaine original",
        "table-th3": "Domaine confidentialité / aperçu",
        "footer-docs": "Notes du projet",
        "footer-text": "VX Link Helper est entièrement open source, local uniquement et sans suivi.",
        "footer-privacy": "Politique de confidentialité",
        "p-title": "Politique de confidentialité",
        "p-intro": "VX Link Helper a été conçu avec la confidentialité comme principe central. Cette politique décrit son fonctionnement local :",
        "p-h1": "1. Aucune collecte de données",
        "p-d1": "Nous <b>ne collectons, stockons, transmettons ni vendons</b> aucune donnée personnelle, valeur du presse-papiers, historique ou journal d’utilisation. Aucune télémétrie ni analyse distante n’est utilisée.",
        "p-h2": "2. Traitement local uniquement",
        "p-d2": "Tout le nettoyage des liens et la réécriture des domaines se font dans le bac à sable du navigateur sur votre appareil. Les URL restent sous votre contrôle.",
        "p-h3": "3. Transparence des autorisations",
        "p-d3": "Les autorisations demandées sont limitées aux fonctions qu’elles activent :",
        "p-l1": "contextMenus : ajoute l’action Copier le lien VX au menu contextuel du navigateur.",
        "p-l2": "clipboardWrite : écrit le lien nettoyé dans le presse-papiers système.",
        "p-l3": "Correspondances d’hôtes spécifiques : injecte des boutons uniquement sur les sites pris en charge.",
        "p-h4": "4. Statistiques des boutiques",
        "p-d4": "Les plateformes de distribution comme le Chrome Web Store, Firefox Add-ons, Edge Add-ons ou Safari peuvent fournir aux mainteneurs des statistiques agrégées d’installation, de version, de région ou d’appareils actifs. Ces statistiques proviennent des boutiques elles-mêmes ; VX Link Helper ne téléverse pas activement vos liens, le contenu du presse-papiers ni votre activité de navigation.",
        "back-home": "Retour à l’accueil",
        "meta-description": "Extension légère et privée qui supprime les paramètres de suivi et génère des liens avec aperçu pour X, Bilibili, Reddit et Pixiv."
    },
    ja: {
        "language-label": "言語",
        "nav-features": "機能",
        "nav-platforms": "対応サイト",
        "hero-title": "よりクリーンで安全なリンクをすぐに共有",
        "hero-subtitle": "軽量でプライバシー重視のブラウザ拡張機能。追跡パラメータを自動で削除し、X、Bilibili、Reddit、Pixiv 向けの埋め込みに適したプレビューリンクを生成します。",
        "store-chrome-small": "ソースと導入",
        "store-firefox-small": "ソースと導入",
        "store-safari-small": "ソースと導入",
        "store-app-small": "モバイル Web",
        "store-zip-small": "開発者モード",
        "btn-chrome": "Chrome ビルド情報",
        "btn-firefox": "Firefox ビルド情報",
        "btn-safari": "Safari ビルド情報",
        "btn-app": "モバイル Web App を開く",
        "btn-zip": "リリースをダウンロード",
        "preview-original": "元のリンク:",
        "preview-arrow": "⬇️ 追跡を削除しホストを書き換え",
        "preview-vx": "クリーンな VX リンク:",
        "url-original": "https://x.com/user/status/1234567890?s=20&t=tracker_code_abc",
        "url-vx": "https://vxtwitter.com/user/status/1234567890",
        "features-title": "VX Link Helper を使う理由",
        "feat1-title": "🔒 100% ローカル処理",
        "feat1-desc": "ブラウザのサンドボックス内だけで動作します。テレメトリもバックエンド解析もなく、完全なオフラインプライバシーを保ちます。",
        "feat2-title": "✨ 美しいプレビューカード",
        "feat2-desc": "通常の URL を vxtwitter のような最適化済みプレビュードメインに変換し、Discord や Telegram などでメディアを正しく表示します。",
        "feat3-title": "⚡ ネイティブ UI への統合",
        "feat3-desc": "高速な DOM オブザーバーで、対応サイトの共有操作の横に VX ショートカットを追加します。",
        "platforms-title": "対応ドメイン変換",
        "table-th1": "プラットフォーム",
        "table-th2": "元のドメイン",
        "table-th3": "プライバシー / プレビュードメイン",
        "footer-docs": "プロジェクト情報",
        "footer-text": "VX Link Helper は完全にオープンソースで、ローカルのみで動作し、追跡はありません。",
        "footer-privacy": "プライバシーポリシー",
        "p-title": "プライバシーポリシー",
        "p-intro": "VX Link Helper はユーザーのプライバシーを中核原則として設計されています。このポリシーはローカルのみの動作を説明します。",
        "p-h1": "1. データ収集ゼロ",
        "p-d1": "個人データ、クリップボードの内容、閲覧履歴、利用ログを<b>収集、保存、送信、販売することはありません</b>。テレメトリやリモート解析もありません。",
        "p-h2": "2. ローカルのみの処理",
        "p-d2": "リンクのクリーンアップとドメイン書き換えはすべて、お使いの端末のブラウザサンドボックス内で実行されます。URL はローカルで処理されます。",
        "p-h3": "3. 権限の透明性",
        "p-d3": "要求するブラウザ権限は、対応する機能に限定されています。",
        "p-l1": "contextMenus: ブラウザのコンテキストメニューに「VXリンクをコピー」を追加します。",
        "p-l2": "clipboardWrite: クリーンなリンクをシステムクリップボードへ書き込みます。",
        "p-l3": "特定ホストの一致: 対応サイトでのみ安全にコピー用ボタンを挿入します。",
        "p-h4": "4. ストア統計について",
        "p-d4": "Chrome Web Store、Firefox Add-ons、Edge Add-ons、Safari などの配布プラットフォームは、インストール数、バージョン、地域、アクティブ端末数などの集計統計をメンテナーに提供する場合があります。これらの統計はストア自体から提供されるものであり、VX Link Helper がリンク、クリップボード内容、閲覧行動を能動的にアップロードすることはありません。",
        "back-home": "ホームへ戻る",
        "meta-description": "追跡パラメータを削除し、X、Bilibili、Reddit、Pixiv 向けのプレビューしやすいリンクを生成する軽量でプライバシー重視の拡張機能。"
    }
};

const languageConfig = {
    en: { htmlLang: "en", dir: "ltr" },
    zh: { htmlLang: "zh-CN", dir: "ltr" },
    "zh-TW": { htmlLang: "zh-TW", dir: "ltr" },
    es: { htmlLang: "es", dir: "ltr" },
    ar: { htmlLang: "ar", dir: "rtl" },
    pt: { htmlLang: "pt", dir: "ltr" },
    fr: { htmlLang: "fr", dir: "ltr" },
    ja: { htmlLang: "ja", dir: "ltr" }
};
const supportedLanguages = new Set(Object.keys(i18nData));
let currentLang = "en";

function normalizeLanguage(lang) {
    if (!lang) return "en";
    const normalized = lang.toLowerCase();
    if (normalized.startsWith("zh-tw") || normalized.startsWith("zh-hk") || normalized.startsWith("zh-mo") || normalized.includes("hant")) return "zh-TW";
    if (normalized.startsWith("zh")) return "zh";
    const primary = normalized.split("-")[0];
    return supportedLanguages.has(primary) ? primary : "en";
}

function setText(id, value) {
    const el = document.getElementById(id);
    if (el && value) el.textContent = value;
}

function setHtml(id, value) {
    const el = document.getElementById(id);
    if (el && value) el.innerHTML = value;
}

function setPreviewLink(id, value) {
    const el = document.getElementById(id);
    if (!el || !value) return;
    el.textContent = value;
    if (el.tagName === "A") el.href = value;
}

function applyTranslations() {
    const data = i18nData[currentLang] || i18nData.en;
    const config = languageConfig[currentLang] || languageConfig.en;
    document.documentElement.lang = config.htmlLang;
    document.documentElement.dir = config.dir;

    document.querySelectorAll("[data-i18n]").forEach(el => {
        const key = el.getAttribute("data-i18n");
        if (data[key]) el.textContent = data[key];
    });

    ["btn-chrome", "btn-firefox", "btn-safari", "btn-zip", "btn-app", "back-home", "p-title", "p-h1", "p-h2", "p-d2", "p-h3", "p-d3", "p-l1", "p-l2", "p-l3", "p-h4", "p-d4"].forEach(id => setText(id, data[id]));
    ["p-intro", "p-d1"].forEach(id => setHtml(id, data[id]));
    setPreviewLink("url-original", data["url-original"]);
    setPreviewLink("url-vx", data["url-vx"]);

    const selectEl = document.getElementById("lang-select");
    if (selectEl) selectEl.value = currentLang;

    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription && data["meta-description"]) {
        metaDescription.setAttribute("content", data["meta-description"]);
    }
}

document.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem("vxlh-lang");
    currentLang = supportedLanguages.has(savedLang) ? savedLang : normalizeLanguage(navigator.language || navigator.userLanguage);
    applyTranslations();

    const selectEl = document.getElementById("lang-select");
    if (selectEl) {
        selectEl.addEventListener("change", (e) => {
            currentLang = supportedLanguages.has(e.target.value) ? e.target.value : "en";
            localStorage.setItem("vxlh-lang", currentLang);
            applyTranslations();
        });
    }
});
